version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: social_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data: